In [1]:
import gym

In [2]:
env = gym.make('MountainCar-v0')
env.reset()
for _ in range(10):
    env.render()
    env.step(env.action_space.sample()) # take a random action

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [9]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(2):
    observation = env.reset()
    for t in range(10):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[-0.00987181  0.03089664  0.04538725 -0.01489523]
[-0.00925388  0.22533928  0.04508934 -0.29291957]
[-0.00474709  0.41979033  0.03923095 -0.57104792]
[ 0.00364872  0.61434081  0.02780999 -0.85111815]
[ 0.01593553  0.80907276  0.01078763 -1.13492806]
[ 0.03211699  0.61381133 -0.01191093 -0.83888145]
[ 0.04439321  0.41885403 -0.02868856 -0.54996797]
[ 0.05277029  0.61436696 -0.03968792 -0.85154997]
[ 0.06505763  0.41980793 -0.05671892 -0.57160643]
[ 0.07345379  0.61567745 -0.06815105 -0.88160466]
[-0.00906485 -0.04024089 -0.0291841  -0.03073035]
[-0.00986967 -0.23493243 -0.0297987   0.2526037 ]
[-0.01456832 -0.03939793 -0.02474663 -0.04932736]
[-0.01535628  0.15606996 -0.02573318 -0.3497142 ]
[-0.01223488  0.35154826 -0.03272746 -0.65039929]
[-0.00520391  0.54711041 -0.04573545 -0.95320558]
[ 0.0057383   0.7428169  -0.06479956 -1.25989988]
[ 0.02059464  0.54858098 -0.08999755 -0.98819523]
[